application: davine-web
version: 1
runtime: go
api_version: go1

handlers:
- url: /(index.html)?
  static_files: public/index.html
  upload: public/index.html
  
- url: /favicon.ico
  mime_type: image/x-icon
  static_files: public/favicon.ico
  upload: public/favicon.ico
  expiration: "30d"

- url: /cron/*
  script: _go_app
  login: admin

- url: /admin/*
  script: _go_app
  login: admin
  secure: always

- url: /(.+\.(css|js|png|ico|txt))
  static_files: public/\1
  upload: public/(.*)

- url: /.*
  script: _go_app
  
inbound_services:
- warmup

admin_console:
  pages:
  - name: Davine Dashboard
    url: /admin/dashboard