application: davine
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: public/index.html
  upload: public/index.html
  expiration: "1d"
  
- url: /about
  static_files: public/about.html
  upload: public/index.html
  expiration: "2d"
  
- url: /cron/*
  script: _go_app
  login: admin

- url: /(.*\.css)
  mime_type: text/css
  static_files: public/\1
  upload: public/(.*\.css)
  
- url: /(.*\.js)
  mime_type: text/javascript
  static_files: public/\1
  upload: public/(.*\.js)

- url: /.*
  script: _go_app
